version: '3.8'
services:
  webapp-debug:
    build: .
    command: "npm run build:run"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - server-debug

  server-debug:
    build: ../3q-server
    command: "npm start"
    restart: unless-stopped
    ports:
      - "9090:9090"
    env_file:
      - "../3q-server/.env"
    stdin_open: true
    tty: true
    volumes:
      - "../3q-server:/app"
    depends_on:
      - db-debug

  db-debug:
    image: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - 3306
    env_file:
      - "../3q-server/.env"
    volumes:
      - "db_debug:/var/lib/mysql"

volumes:
  db_debug:
