version: '3'
services:
  webapp-prod:
    build: .
    ports: 
      - "8080:8080"
    profiles:
      - "prod"

  webapp-debug:
    build: .
    command: "npm run build:run"
    ports:
      - "8080:8080"
    profiles:
      - "debug"
    volumes:
      - ".:/app"
      
  server-prod:
    build: "../3q-server"
    ports:
      - "9090:9090"
    profiles:
      - "prod"

  server-debug:
    build: ../3q-server
    command: "npm start"
    ports:
      - "9090:9090"
    profiles:
      - "debug"
    volumes:
      - "../3q-server:/app"
