version: '3.8'
services:
  webapp:
    build: .
    restart: unless-stopped
    ports: 
      - "8080:8080"
    depends_on:
      - server
      
  server:
    build: "../3q-server"
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - db

  db:
    image: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - 3306
    env_file:
      - "../3q-server/.env"
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:
